"""add created_by to sales

Revision ID: 247cb79b476a
Revises: c99f105b4d7e
Create Date: 2026-01-13 18:06:09.171404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '247cb79b476a'
down_revision: Union[str, None] = 'c99f105b4d7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sales', sa.Column('created_by', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'sales', 'user', ['created_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'created_by')
    # ### end Alembic commands ###
