"""add sold_by to sales

Revision ID: 25eeac94993d
Revises: 68c08341f5c9
Create Date: 2026-01-07 19:32:28.423796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '25eeac94993d'
down_revision: Union[str, None] = '68c08341f5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sales_id', table_name='sales')
    op.drop_table('sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('stock_id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('quantity_sold', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('selling_price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('total_amount', mysql.DECIMAL(precision=12, scale=2), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], name='sales_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_sales_id', 'sales', ['id'], unique=False)
    # ### end Alembic commands ###
