"""add stocks relationship to products

Revision ID: 68c08341f5c9
Revises: 06b2a8eb4009
Create Date: 2026-01-06 18:37:09.597443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '68c08341f5c9'
down_revision: Union[str, None] = '06b2a8eb4009'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
