"""Fix updated_at onupdate for products

Revision ID: f95e2b98f62b
Revises: 247cb79b476a
Create Date: 2026-01-18 21:18:33.467032

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f95e2b98f62b'
down_revision: Union[str, None] = '247cb79b476a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
